### ISSUE TITLE
Where does useMemo come from? 

### ISSUE THREAD

**Issue by patikanji** [andyrichardson/fielder#266]
There is no mention in the guides, but exists in sample codes.

**Comment by andyrichardson** [comment]
Hey @patikanji, useMemo is provided by React as part of the hooks API. You can find out [more about it here](https://reactjs.org/docs/hooks-reference.html#usememo).

The reason you want to memoize your validation function is so that Fielder can work out whether the validation function has changed or not.

**Comment by patikanji** [comment]
@andyrichardson Thanks. I just come to react world (via NextJS) after years oh PHP. It seems promising to use fielder since I often work with long and complex forms.

**Comment by andyrichardson** [comment]
No worries @patikanji :+1: 

Definitely check out the official docs for React, they're a really strong source!

As for Fielder, here are [some examples](https://fielder.andyrichardson.dev/examples) and a [tutorial video](https://www.youtube.com/watch?v=wSorSlCkJwk) to help you get started.

**Comment by patikanji** [comment]
Sure @andyrichardson. I'm reading the doc right now after watching your video in my Flipboard feeds.
